GET http://localhost:8000/

GET http://localhost:8000/cli

GET http://localhost:8000/cli/<id>

GET http://localhost:8000/list

GET http://localhost:8000/prod

GET http://localhost:8000/prod/<id>

GET http://localhost:8000/prod?<query>&<page>&<pagination>

GET http://localhost:8000/user

GET http://localhost:8000/user/<id>

POST http://localhost:8000/oder/<id>/move

POST http://localhost:8000/oder/new

POST http://localhost:8000/user/new